-- ============================================================
-- Kuma 拨测矩阵 seed —— 监控定义配置即代码（密码一律 [CHANGE_ME] 占位）
-- 来源：ops-kuma SQLite monitor 表 10-04 实际运行态导出
-- 用途：D5 迁服务器/容器重建时恢复 11 条监控（手动导入或 sqlite3 kuma.db < 本文件）
-- 纪律：密码不进 git；导入后须回填真实密码（mysql/redis 从目标容器 env 取）
-- 配套：组挂载见底部 monitor_group 段（对应 /status/ops 状态页两个分面）
-- ============================================================
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO monitor (id,name,active,user_id,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,timeout,conditions) VALUES (4,'运维面板',1,1,60,'http://ops-homepage:3000','http',2000,3,10,'["200-299"]',60,'GET',47.2,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,user_id=excluded.user_id,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,timeout=excluded.timeout,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (10,'ops-homepage',1,60,'http://ops-homepage:3000','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (11,'ops-semaphore',1,60,'http://ops-semaphore:3000','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (12,'ops-kuma-self',1,60,'http://localhost:3001','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (13,'ops-adminer',1,60,'http://ops-adminer:8080','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (14,'ops-jenkins',1,60,'http://ops-jenkins:8080/login','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (15,'ops-gitea',1,60,'http://ops-gitea:3000','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (16,'clinic-grafana',1,120,'http://clinic-grafana:3000','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,url,type,weight,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,conditions) VALUES (17,'clinic-frontend',1,120,'http://clinic-frontend:80','http',2000,1,10,'["200-299"]',60,'GET',1,'[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,url=excluded.url,type=excluded.type,weight=excluded.weight,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,type,weight,hostname,port,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,database_connection_string,database_query,conditions) VALUES (18,'clinic-mysql',1,120,'mysql',2000,'clinic-mysql',3306,1,10,'["200-299"]',60,'GET',1,'mysql://USER:[CHANGE_ME]@clinic-mysql:3306/clinic','SELECT 1','[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,type=excluded.type,weight=excluded.weight,hostname=excluded.hostname,port=excluded.port,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,database_connection_string=excluded.database_connection_string,database_query=excluded.database_query,conditions=excluded.conditions;
INSERT INTO monitor (id,name,active,interval,type,weight,hostname,port,maxretries,maxredirects,accepted_statuscodes_json,retry_interval,method,expiry_notification,database_connection_string,radius_password,conditions) VALUES (19,'clinic-redis',1,120,'redis',2000,'clinic-redis',6379,1,10,'["200-299"]',60,'GET',1,'redis://:[CHANGE_ME]@clinic-redis:6379','[CHANGE_ME]','[]') ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=excluded.active,interval=excluded.interval,type=excluded.type,weight=excluded.weight,hostname=excluded.hostname,port=excluded.port,maxretries=excluded.maxretries,maxredirects=excluded.maxredirects,accepted_statuscodes_json=excluded.accepted_statuscodes_json,retry_interval=excluded.retry_interval,method=excluded.method,expiry_notification=excluded.expiry_notification,database_connection_string=excluded.database_connection_string,radius_password=excluded.radius_password,conditions=excluded.conditions;
-- 状态页（slug=ops，published）与组挂载
INSERT INTO status_page (id,slug,title,description,icon,theme,published,search_engine_index,show_tags,show_powered_by,auto_refresh_interval)
SELECT 1,'ops','运维平台状态页','六件套+clinic 业务栈 心跳一览（Kuma 拨测矩阵）','/icon.svg','auto',1,0,0,0,60
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, published=excluded.published;
INSERT INTO `group` (id,name,public,active,weight,status_page_id) VALUES (1,'平台面板（ops 六件套）',1,1,1000,1),(2,'业务监控（clinic 栈）',1,1,900,1)
ON CONFLICT(id) DO UPDATE SET name=excluded.name, public=excluded.public;
DELETE FROM monitor_group WHERE group_id IN (1,2);
INSERT INTO monitor_group (monitor_id,group_id) VALUES (4,1),(10,1),(11,1),(12,1),(13,1),(14,1),(15,1),(16,2),(17,2),(18,2),(19,2);
COMMIT;
